### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by WigF1**
Fixed product naming
Fixed UI changes
Fixed some typos
Fixed markdown issues
Corrected names so they are now consistent with MCT PPTx and MS Learn titles / nomenclature

Every module affected.

### CODE REVIEW

**Comment by MScalopez** [comment]
Reviewing suggested changes

**Comment by WigF1** [comment]
Any updates?

**Comment by WigF1** [comment]
We're almost at the end of January. I'm curious as to what was stopping the PR be merged when first submitted almost 2 months ago?

**Comment by MScalopez** [comment]
@WigF1, thank you for pointing out all this issues.  We had made a push of some of the same changes we also identified with the product name change back on December 16th.  That said, you found many other issues that we had not identified, thank you for that, so since a merge was no longer possible, we went ahead and made those additional changes you suggested manually to 13 of the 26 md files.  I made a note about that on each of those files.  I will go ahead and close this request.  Again thank you for all your help.  And thank you for your patience.

**Pull request closed without merging**
