### PR TITLE
Update 04-sdk-connect.md

### PR DESCRIPTION
**Pull request by ealsur**
The final code snippet does not compile

# Module: 04
## Lab/Demo: 04

Fixes:
image

- The code snippet does not compile, `using` lines should be all together, should be:

```
using System;
using System.Linq;
using Microsoft.Azure.Cosmos;
```

### CODE REVIEW

**Comment by seesharprun** [comment]
I just tried this out with a blank line and couldn't reproduce your issue.

```csharp
using System;
using System.Linq;

using Microsoft.Azure.Cosmos;

Console.WriteLine("Testing!");

// Emulator credentials
string endpoint = "https://localhost:8081";
string key = "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==";

CosmosClient client = new (endpoint, key);

AccountProperties props = await client.ReadAccountAsync();

Console.WriteLine($"Identifier:\t{props.Id}");
```

I tested this in the /learn module using .NET version **6.0.100**.

It was able to compile successfully.

image

**Comment by ealsur** [comment]
@seesharprun I tested this inside the Lab VM that is provisioned, the error description was from there (as you can see in the error path) and the content of the file was the suggestion (I copy/pasted the entire content). The only way for the error to go away was to remove the line between the using statements.

**Comment by seesharprun** [comment]
That's super weird. I have seen that error before when the project has using statements and no actual executable lines of code. For a top-level statement[s] (script) app, it cannot compile with just using statements since the compiler doesn't know where to start the Main method, it needs at least one statement that can be executed.

**Comment by ealsur** [comment]
@seesharprun  I ran the lab again just to make sure and I get the error:

image

If I remove the line inbetween using:

image

From the screenshot, you can see it is the same Lab machine, same folder (the one for this snippet, 04-sdk-connect)

Code with `dotnet build` error:

```
using System;
using System.Linq;

using Microsoft.Azure.Cosmos;

string endpoint = "<cosmos-endpoint>";
string key = "<cosmos-key>";

CosmosClient client = new (endpoint, key);

AccountProperties account = await client.ReadAccountAsync();

Console.WriteLine($"Account Name:\t{account.Id}");
Console.WriteLine($"Primary Region:\t{account.WritableRegions.FirstOrDefault()?.Name}");
```

Code that builds:

```
using System;
using System.Linq;
using Microsoft.Azure.Cosmos;

string endpoint = "<cosmos-endpoint>";
string key = "<cosmos-key>";

CosmosClient client = new (endpoint, key);

AccountProperties account = await client.ReadAccountAsync();

Console.WriteLine($"Account Name:\t{account.Id}");
Console.WriteLine($"Primary Region:\t{account.WritableRegions.FirstOrDefault()?.Name}");
```

I think the problem is when the code is pasted from the Instructions, I was able to repro only when doing that. If I manually type the entire code, then it does not happen. I don't know if it's because of some line break?

**Comment by ealsur** [comment]
Since the repro is very flimsy, I will close the issue. It could be because of a line break character

**Comment by seesharprun** [comment]
I still think tracking that copying the code creates line breaks is a worthwhile endeavor. Would it be better as an issue?

We had some wonky stuff go on when testing the labs around line breaks when copied from the LODS interface.

**Pull request closed without merging**
