### PR TITLE
Update 04-sdk-connect.md

### PR DESCRIPTION
**Pull request by ealsur**
Ideally we just want people to use whatever is latest, otherwise they will keep using older SDKs

# Module: 04
## Lab/Demo: 04

- Remove version specific in the links and snippet

### CODE REVIEW

**Comment by seesharprun** [comment]
As a conflicting MCT opinion, I would say locking the labs down to a specific version helps prevent any last-second lab failures due to the library being updated between when the labs are validated and delivering the class. This library is updated about once a month, so that could very well happen. It's not uncommon for an SDK library to introduce a breaking change that requires a small fix to lab steps.

This is something that was experienced a lot in AZ-204. Any time a library is updated, we ran through the appropriate labs and did a PR moving the lab steps forward to the latest version of the library.

**Comment by ealsur** [comment]
As far as updating the whole lab between version updates, the only comment is that we release updates to the SDK every couple of weeks, so the Lab update would need to be in a short cycle I guess?

**Comment by seesharprun** [comment]
It was just a differing opinion. If there's a high confidence that minor version updates won't break the labs, then remove the version from the labs by all means.

The only other thing to watch is the labs that start with the library pre-installed. Those labs would need to be updated regularly when the SDK is updated.

**Comment by ealsur** [comment]
There should be no breaks (we verify that in our own release gates), although I cannot say the same for other libraries 😄

**Comment by seesharprun** [comment]
I did some more digging and stumbled across [floating NuGet package versions](https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#floating-versions).

Basically, the lab files in this repo could say ``3.*`` in their csproj file, and we don't have to worry about manual versioning.

I wish I knew about this a few months ago 😆

**Comment by ealsur** [comment]
Sounds very cool! And could be the answer 😄

**Review by MScalopez — COMMENTED** [review]
That will work

**Pull request merged**
